# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LYPhoto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYPhoto
  
  # 自动布局
  pod 'SnapKit'
  

  target 'LYPhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYPhotoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
