# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HelloMetal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloMetal
  
  # 自动布局
  
  pod 'SnapKit'

  target 'HelloMetalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloMetalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
